- name: "cluster {{ ClusterContext }} : Create NameSpace"
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    context: "{{ ClusterContext }}"
    name: "{{ Namespace }}"
    state: present

- name: "cluster {{ ClusterContext }} : Deploy Gitlab Runner"
  kubernetes.core.helm:
    name: "{{ Name }}"
    chart_ref: "{{ Chart }}"
    chart_version: "{{ Version }}"  
    context: "{{ ClusterContext }}"
    release_namespace: "{{ Namespace }}"
    values:
      enabled: true
      rbac:
        create: true
        clusterWideAccess: true
      gitlabUrl: "{{ GitlabURL }}" 
      runnerRegistrationToken: "{{ GitlabToken }}" 
      runners:
        executor: "kubernetes"
      service:
        enabled: true
      metrics:
        serviceMonitor:
          enabled: true
          labels:
            release: prometheus
