- name: "cluster {{ ClusterContext }} Create Namespace/{{ Namespace }}"
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    context: "{{ ClusterContext }}"
    name: "{{ Namespace }}"
    state: present

- name: "cluster {{ ClusterContext }} Clean OLD Secret"
  shell: "kubectl delete secret --all -n  {{ Namespace }}"
  ignore_errors: yes
  when: ExtraVars.secrets is defined

- name: "cluster {{ ClusterContext }} Create Generic-Secret/{{ item.name }}"
  shell: ' kubectl create secret generic {{ item.name }}              \
           --from-literal={{ item.key }}="{{ item.vaule }}"           \
           -n {{ Namespace }} '
  loop: "{{ ExtraVars.secrets }}"
  when: ExtraVars.secrets is defined

- name: "cluster {{ ClusterContext }} Deploy Chart/{{ Name }}"
  kubernetes.core.helm:
    name: "{{ Name }}"
    chart_ref: "{{ Chart }}"
    chart_version: "{{ Version }}"
    context: "{{ ClusterContext }}"
    release_namespace: "{{ Namespace }}"
    values: "{{ lookup('template', TemplateFile) | from_yaml }}"

- name: Waiting for {{ Name }} RES Ready
  shell: "kubectl get pods -n {{ Namespace }} | grep -v Running | awk 'NR>1'"
  register: cluster_stats
  until:
    - 'cluster_stats.stdout == ""'
  retries: 40
  delay: 10
 
- name: Show Debug Info
  debug: var=cluster_stats verbosity=0

